Repository acm-ucr/CSE-AI-resources, pull requests merged in 2025-01, with the labels that each got.

#15 Navigation Component
  public/UCRLogo.svg
  src/app/layout.tsx
  src/components/naviagtion.tsx
  src/components/navigation.tsx
  src/data/nav.ts
Labels: ready to review, ready to merge

#19 Projects & Research Component
  package-lock.json
  src/app/page.tsx
  src/components/projects/research.tsx
Labels: ready to review, ready to merge

#24 Added Welcome Component
  src/components/home/welcome.tsx
  tailwind.config.ts
Labels: ready to review, do not merge, ready to merge

#35 created business component
  src/components/projects/business.tsx
Labels: ready to review

#16 Made About Us Component *updated
  src/components/home/about.tsx
Labels: do not merge

#17 Created education componenent with header and text
  src/components/home/education.tsx
Labels: do not merge

#40 Videos
  src/app/resources/page.tsx
  src/components/resources/carousel.tsx
  src/components/resources/videos.tsx
  src/data/videos.ts
Labels: ready to review
