Repository acm-ucr/CSE-AI-resources, pull requests merged in 2025-02, with the labels that each got.

#67 navigation component - on select
  src/components/navigation.tsx
Labels: ready to review

#20 Bananazr crazy/recent news data mapping
  src/app/page.tsx
  src/components/home/news.tsx
  src/data/news.ts
Labels: ready to review

#56 Dropdown
  package-lock.json
  package.json
  public/bluetriangle.svg
  public/yellowtriangle.svg
  src/components/home/dropdown.tsx
  src/components/home/education.tsx
  src/data/courses.ts
Labels: ready to review

#70 Margin and Spacing Fix
  src/components/projects/medical.tsx
  src/components/projects/professionals.tsx
  src/components/projects/research.tsx
  src/components/resources/articles.tsx
  src/components/resources/external.tsx
  src/components/resources/notes.tsx
  src/components/resources/videos.tsx
Labels: ready to review

#81 added mobile navigation
  src/components/navigation.tsx
Labels: ready to review

#66 Career
  package-lock.json
  package.json
  src/app/career/page.tsx
  src/components/projects/career.tsx
  tsconfig.json
Labels: ready to review, ready to merge

#94 made videos component responsive
  public/mock.png
  public/mock.webp
  src/components/resources/videos.tsx
  src/data/news.ts
Labels: ready to review

#87 Articles Responsiveness
  src/components/resources/articlelist.tsx
  src/components/resources/articles.tsx
Labels: ready to review

#61 Made Faculty component
  src/app/projects/page.tsx
  src/components/projects/faculties.tsx
  src/components/projects/faculty.tsx
  src/data/faculty.ts
Labels: ready to review

#106 Responsive design for Professional section
  src/components/projects/professionals.tsx
Labels: ready to review

#89 404 Page
  package-lock.json
  package.json
  src/app/not-found.tsx
Labels: 404 page
